CI check for file-header added file-header check using github.com/kunalkushwaha/ltag
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

diff --git a/script/validate/fileheader b/script/validate/fileheader
--- a/script/validate/fileheader
+++ b/script/validate/fileheader
@@ -17,11 +17,10 @@
 
 set -eu -o pipefail
 
-if ! command -v git-validation; then
-    >&2 echo "ERROR: git-validation not found. Install with:"
-    >&2 echo "    go get -u github.com/vbatts/git-validation"
+if ! command -v ltag; then
+    >&2 echo "ERROR: ltag not found. Install with:"
+    >&2 echo "    go get -u github.com/kunalkushwaha/ltag"
     exit 1
 fi
 
-verbosity="${DCO_VERBOSITY--v}"
-GIT_CHECK_EXCLUDE="./vendor:./script/validate/template" git-validation "$verbosity" -run DCO,short-subject,dangling-whitespace
+ltag -t script/validate/template --check -v
